### ISSUE TITLE
StateOutOfSync: Failed to apply patches

### ISSUE THREAD

**Issue by cfarm6** [JuliaPluto/PlutoSliderServer.jl#101]
When converting this notebook ([link to github gist](https://gist.github.com/cfarm6/9af7a222479f7c70644d1217b29bc631)) to a slider server notebook, the notebook returns a StateOfOutSync error after uploading a file and then trying to change the model variable. The notebook works correctly inside of a pluto notebook but fails to update after uploading a file.

The full error returned in the web console is:
```code
#######################**************************########################
PlutoError: StateOutOfSync: Failed to apply patches.
Please report this: https://github.com/fonsp/Pluto.jl/issues adding the info below:
failing path: status_tree.subtasks.run.subtasks.evaluate.subtasks.1.finished_at 
notebook previous value: Not Found
patch: undefined
#######################**************************########################
Error: [Immer] minified error nr: 15 'status_tree/subtasks/run/subtasks/evaluate/subtasks/1/finished_at'. 
Find the full error at: https://bit.ly/3cXEKWf
```

**Comment by cfarm6** [comment]
@fonsp

**Comment by fonsp** [comment]
This will be fixed in the upcoming Pluto release 🎉
