### ISSUE TITLE
Wrong bond connections graph behavior

### ISSUE THREAD

**Issue by ctrekker** [JuliaPluto/PlutoSliderServer.jl#117]
The following notebook will reproduce the issue:
![Screenshot from 2023-06-07 12-10-07](https://github.com/JuliaPluto/PlutoSliderServer.jl/assets/22894011/e74b3813-98bb-4ff9-82d9-1a6246a1df46)

The value of `f` depends on both `x` and `y`, implying that `x` and `y` are codependent. It seems like PlutoSliderServer's analysis doesn't recognize this:
![Screenshot from 2023-06-07 12-13-31](https://github.com/JuliaPluto/PlutoSliderServer.jl/assets/22894011/01b4d50f-ddae-4696-82e9-e6e0adcb2b21)

I haven't done much more testing beyond finding this simplified MWE, but it seems this is an issue with `codependents` and friends, since Pluto calculates the topology of this notebook without any issues.

**Comment by fonsp** [comment]
super nice! can you add this to one of the test notebooks?

- fons

**Comment by Pangoraw** [comment]
This look likes https://github.com/fonsp/Pluto.jl/issues/2427 so maybe the bug is only on 1.9.

**Comment by ctrekker** [comment]
> This look likes [fonsp/Pluto.jl#2427](https://github.com/fonsp/Pluto.jl/issues/2427) so maybe the bug is only on 1.9.

I bet that's it! That looks like pretty much an identical bug, and the issue was fixed after I updated Pluto from `0.19.9` to `>=0.19.19` in the slider server project toml.
