### ISSUE TITLE
Get visual feedback about notebook running status

### ISSUE THREAD

**Issue by disberd** [JuliaPluto/PlutoSliderServer.jl#121]
As discussed on [zulip](https://julialang.zulipchat.com/#narrow/stream/243342-pluto.2Ejl/topic/Visual.20cue.20of.20running.20computation.20on.20SliderServer), it would be very helpful to see which cells are running on the notebook on the server especially for long running computations.

Another interesting point raised on [discourse](https://discourse.julialang.org/t/host-pluto-server-in-the-cloud-eg-digital-ocean/92737/10?u=disberd) would be having the possibility of relaying logs back to the clients, though I am not sure how feasible or easy that is.

Tagging @ctrekker as he mentioned the first part would be rather simple to implement.

**Comment by ctrekker** [comment]
Linking #64 and fonsp/Pluto.jl#2130
