### ISSUE TITLE
Large statefile with `baked_statefile = true` fails to open

### ISSUE THREAD

**Issue by jbrea** [JuliaPluto/PlutoSliderServer.jl#132]
I am stuck with the following error message for one of my notebooks
![23 12 08T09:02:49](https://github.com/JuliaPluto/PlutoSliderServer.jl/assets/12857162/9e97ec22-073d-4a9c-9c99-65b089f8c67f)

Funnily enough, the page loads just fine in some browsers (e.g. qutebrowser) but I get the above error message in others (e.g. firefox).

Any ideas?

**Comment by fonsp** [comment]
Can you copy and paste the full contents of the page?

**Comment by fonsp** [comment]
and could you say a bit more about what steps you took to get here?

**Comment by jbrea** [comment]
Thanks. Here is the [url of the hosted notebook](https://bio322.epfl.ch/notebooks/pca.html) and [this is the source](https://github.com/jbrea/MLCourse/blob/main/notebooks/pca.jl) and the [Dockerfile](https://github.com/jbrea/MLCourse/blob/main/Dockerfile).

**Comment by jbrea** [comment]
Could it be that this happens when the statefile exceeds a certain size? I removed some of the embedded images and now the page seems to load fine.

**Comment by fonsp** [comment]
Interesting! Yes the problem is probably that the statefile gets too big.

For PlutoSliderServer I would always recommend setting `Export_baked_statefile = false`, not sure why that's not the default.

That way, the statefile is stored in a separate file, instead of base64-encoded in a javascript string. Then there is no file size limit.

**Comment by fonsp** [comment]
I think we should:
1. Find out what the maximum size is and show an `@error` when it happens.
2. Consider making baked_statefile=true the default
