### ISSUE TITLE
Escaped characters in URLs with hashes working for deno fileserver but not Python

### ISSUE THREAD

**Issue by Pat-Laub** [JuliaPluto/PlutoSliderServer.jl#45]
Firstly, thanks for producing this really cool software! I'm planning to use Pluto (especially with precomputed static outputs) as much as possible now :) 

I was just trying the precomputed static html branch (though I would guess this behaviour is unrelated to the pre-computation), and found that sometimes I would get 404 error when trying to load the bond connections file, and the dynamic content would fail.

Specifically, I generated a static HTML output using

```
PlutoSliderServer.export_notebook("basic3.jl", Precompute_enabled=true)
```

on the [basic3.jl](https://github.com/JuliaPluto/PlutoSliderServer.jl/blob/static-export-1/test/basic3.jl) test file, then if I ran

```
deno run --allow-net --allow-read https://deno.land/std@0.115.0/http/file_server.ts .  --port 8000
```

the localhost:8000/basic3.html page would work as expected, whereas if instead I tried Python's built-in server

```
python3 -m http.server 8000
```

then the Javascript console would show a 404 error trying to load bondconnections and the interactivity would not work anymore.

Javascript prints out the same notebook hash in both cases, `7uehaeBoJorFiesT4uKI7Rl3bFJcsQwdILATmeaacfs=`, and both links request

`http://localhost:8000/bondconnections/7uehaeBoJorFiesT4uKI7Rl3bFJcsQwdILATmeaacfs%3D`

however Python's server will only load this file if the URL used is

`http://localhost:8000/bondconnections/7uehaeBoJorFiesT4uKI7Rl3bFJcsQwdILATmeaacfs%253D`

The difference appears to be a different escaping mechanism for the URL (Python wanting the escaped characters to have '25' after each '%').

Having the Python server supported is not important, I was simply hoping to put the precomputed html files onto [Github Pages](https://pat-laub.github.io/test-docs/explore.html) and I spotted this problem there. Using Python locally was just a convenient way to reproduce this error. I'm not a web developer, so I hope this isn't simply some trivial error caused by my ignorance! Thanks.

**Comment by fonsp** [comment]
Thanks for narrowing down on the problem! I am currently taking a small break from PlutoSliderServer but I will pick it up in about a month :)

**Comment by fonsp** [comment]
I just updated https://github.com/JuliaPluto/PlutoSliderServer.jl/pull/29 from `main` which includes my fix! Try again now

**Comment by fonsp** [comment]
Also @Pat-Laub please let me know how https://github.com/JuliaPluto/PlutoSliderServer.jl/pull/29 is working for you! Are there any missing features? Is it easy to write notebooks that will work precomputed? Do you often get too many possibilities?
