### ISSUE TITLE
Request hash not found  - Issue caused by escape character when running nginx reverse proxy

### ISSUE THREAD

**Issue by cenmir** [JuliaPluto/PlutoSliderServer.jl#46]
Hello!

First of all, thanks for all the effort in creating these tools!

# The issue

When running ````PlutoSliderServer.run_directory(".")```` and accessing the webserver using nginx as a reverse proxy like this:

````
location /pluto/ {
   proxy_pass         "http://127.0.0.1:2345/";
}
````

sometimes I get an error, reported by the PlutSliderServer process, of the type:
````
┌ Info: Request hash not found. See errror hint in my source code.
└   notebook_hash = "EJV5zDLtcW"
````
The error happens on page load and each time the slider is adjusted.

The corresponding published notebook:
![](https://i.imgur.com/VMxg0EO.png)

as can be seen from the screenshot, somehow the URL containing the hash with the forward slash is escaped and causes a problem. This only happens when forwarding `/pluto/` to `http://127.0.0.1:2345/`. This issue does not exist if the root is forwarded like so:

````
location / {
    proxy_pass         "http://127.0.0.1:2345";
}
````

I have changed my notebooks slightly by adding whitespaces in the text to generate different hashes and each time a forward slash is in the hash, this issue arises.

## For reference 
Here are examples that cause the issue:
[Example 3](https://i.imgur.com/WANYoaT.png),
[Example 4](https://i.imgur.com/mbml3RY.png)

Examples with hashes that do not cause issues:
[Example 1](https://i.imgur.com/egCcYkn.png),
[Example 2](https://i.imgur.com/tgjQVDt.png),
[Example 1](https://i.imgur.com/y7P0fON.gif),
[Example 2](https://i.imgur.com/LutXDz1.gif)

## My setup
I am using the default settings for PlutoSliderServer (v0.3.3), julia version 1.7.0, nginx version 1.14.1, CentOS version 8.

I don't know if the hashing procedure can be altered to avoid certain characters or if this is an nginx configuration issue.

Issues #42 and #45 seem to be similar to this.

Now, I could fiddle around with whitespaces to find hashes that do work, but it's kind of an inelegant solution. 

How did you avoid these issues when creating the Computational Thinking site?

**Comment by leephillips** [comment]
I had almost the same problem on Apache, but with no difference between proxying / or /something/. The solution (so far - early in testing) was to add the `nocanon` keyword to the ProxyPass directive. This passes the URL raw to the proxy server. I don’t know what the equivalent is on Nginx, but I think this is where the problem is: the webserver rewriting the URL.

**Comment by cenmir** [comment]
Thanks for pointing me in the right direction, knowing what terms to search for and focusing attention to nginx, I found this solution which solved my problem:

https://stackoverflow.com/questions/28684300/nginx-pass-proxy-subdirectory-without-url-decoding/37584637#37584637

Some URI rewrite magic did the trick! Special characters like + and / are no longer beeing processed by nginx.

```
location /notebooks/ {
   rewrite ^ $request_uri;
   rewrite ^/notebooks/(.*) $1 break;
   return 400;
   proxy_pass http://127.0.0.1:2345/$uri;
}
```

**Comment by fonsp** [comment]
I opened #57 to avoid the special `+` and `/` characters altogether, this should solve this issue without requiring a special nginx config 🌟
