### ISSUE TITLE
Sliders are greyed out using github pages

### ISSUE THREAD

**Issue by Ron-27** [JuliaPluto/PlutoSliderServer.jl#80]
First of all I want to say thank you so much for the developers. This is an amazing tool!
Second, I was able to use github pages to host my notebook, but for some reason the sliders are greyed out in the notebook (I only use the bind feature). Is there any step I'm missing in the configurations? Seems like it should work from what I read in the readme file.

**Comment by fonsp** [comment]
Hey @Ron-27 ! You currently need a live running slider server to support interactive sliders, the github action alone will only generate the static HTML file.

Also take a look at #29, perhaps this is what you expected?
