### ISSUE TITLE
With version 0.3.12 I get 404 for all notebooks not in the root folder

### ISSUE THREAD

**Issue by jbrea** [JuliaPluto/PlutoSliderServer.jl#88]
Recently I updated PlutoSliderServer for my [course material](https://github.com/jbrea/MLCourse) from 0.3.11 to 0.3.12. Everything worked normally, except that after loading the notebooks they were not accessible at the usual address, e.g. [https://bio322.epfl.ch/notebooks/pca.html](https://bio322.epfl.ch/notebooks/pca.html) showed me just a 404 error.
The index page, however, loaded normally.

Meanwhile I went back PlutoSliderServer to 0.3.11, because I wanted to serve the pages and I couldn't figure out what was wrong.

**Comment by fonsp** [comment]
Thanks! We are looking into this!

**Comment by fonsp** [comment]
(This issue is about the situation where PlutoSliderServer is also serving the HTML files, and you are viewing them by visiting the server's IP address directly. So this is not about the GitHub export feature.)

**Comment by Pangoraw** [comment]
The actual fix is https://github.com/JuliaPluto/PlutoSliderServer.jl/pull/91, not https://github.com/fonsp/Pluto.jl/pull/2284!

**Comment by fonsp** [comment]
Right! This will be fixed by PlutoSliderServer 0.3.14, you don't need Pluto 0.19.12.
